# NB we must have already built 'flask_iscpif_regcomex' and 'minidoors' images
#                                =====================       =========
    version: '2'
    services:

      mysql_regcomex:
        image: mysql
        environment:
         - MYSQL_ROOT_PASSWORD=very-safe-pass
        volumes:
         - ../../data/shared_mysql_data:/var/lib/mysql

      # in the future: external service (=> just remove doors_test & change DOORS_HOST)
      doors_test:
        image: minidoors
        ports:
         - "32789:8989"
         # POSSIBLE volume for h2 DB itself

      comex_test:
        image: flask_iscpif_regcomex
        depends_on:
         - mysql_regcomex
         - doors_test
        links:
         - mysql_regcomex:comex_db_backend
         - doors_test:doors_backend
        environment:
         - HOST=0.0.0.0                # script will bind server to this address
         - DEBUG_FLAG=false
         - SQL_HOST=comex_db_backend   # script will read/write sql to this host
         #- DOORS_HOST=doors_backend   # script will log/register users to this host
         #- DOORS_PORT=8989            # original port on doors_backend
         - DOORS_HOST=localhost
         - DOORS_PORT=32789            # forwarded port we're accessing in tests

      #TODO add php legacy communityexplorer site
