    version: '2'
    services:

      comex_db_test:
        image: mysql
        environment:
         - MYSQL_ROOT_PASSWORD=very-safe-pass
        volumes:
         - ../../data/shared_mysql_data:/var/lib/mysql

      doors_test:
        image: minidoors:latest
        build: ./minidoors
        ports:
         - "32789:8989"
        volumes:
         - ../../../shared_minidoors_data:/root/.doors
     # in the future: external service (=> just remove doors_test
     #                                     & change DOORS_HOST
     #                                          and DOORS_PORT)

      comex_test:
        image: comex2_services:testing
        build: ./comex2_services
        # logs will show all that's printed to STDOUT with tty:true
        tty: true
        ports:
         # we expose the entire contained nginx
         - "8080:80"
        links:
         - comex_db_test
        volumes:
         # /!\ this uses outside conf to replace :contained conf
         - ../../config:/comex2/config
         # similar logic used to expose inner logs
         - ../../logs:/comex2/logs
        environment:
            # override values from parametres_comex.ini
            # for a double reason:
            #   - both apps have ENV vals preempt INI vals
            #   - if we're here (in docker-compose) then by definition the mysql must be coming from comex_db_test container
            - SQL_HOST=comex_db_test
            - SQL_PORT=3306
