    version: '2'
    services:

      comex_db_test:
        image: mysql
        environment:
         - MYSQL_ROOT_PASSWORD=very-safe-pass
        volumes:
         - ../../data/shared_mysql_data:/var/lib/mysql

      doors_test:
        image: minidoors:latest
        build: ./minidoors
        ports:
         - "32789:8989"
        volumes:
         - ../../../shared_minidoors_data:/root/.doors
     # in the future: external service (=> just remove doors_test
     #                                     & change DOORS_HOST
     #                                          and DOORS_PORT)

      comex_test:
        image: comex2_services:testing
        build: ./comex2_services
        ports:
         - "32790:9090"
        links:
         - comex_db_test
         - doors_test
        volumes:
         # /!\ this uses outside conf to replace :contained conf
         - ../../config:/comex2/config
